sudo: required
install:
  - sudo apt-get update
  - sudo apt-get install -y libxml2-dev libreadline-dev valgrind
  - ./autogen.sh
  - ./.prepare_src_pkg.sh
  - sed -i '41s/ENOENT/ENOENT || errno == EINVAL/' gnulib/tests/test-readlink.h
language: c
notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#augeas"
script: ./configure && make && make check && ./src/try valgrind
after_success: ./.ppa_publish.sh
